it('inputs change the shadow', ()=> {
    cy.visit('http://localhost:3000');
    cy.get('ul').find('a:first')
    .next().click()
    cy.get('#log-wrapper')
    .find('input:first')
    .type('mycypress@test.com')
    .next().type('mytest')
    .next()
    .click()
    cy.get('#ske-projects-display:first')
    .click()
    cy.get('.shape_709:first')
    .click({force: true})
    cy.get('#newBorderWidth')
    .click()
    .type('4' + "{enter}")
    cy.get('#newBorderType')
    .select('dotted')
    cy.get('.shape_709:first')
    .should('have.css', 'border')
    .and('match', /4px dotted rgb\(0, 0, 0\)/)

})